name: Deploy Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vash-nash-bot:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-test:
    needs: build
    runs-on: ubuntu-latest
    environment: test
    
    steps:
      - name: Deploy to test server
        uses: appleboy/ssh-action@master
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          MESSAGE_THREAD_ID: ${{ secrets.MESSAGE_THREAD_ID }}
          GITHUB_SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: BOT_TOKEN,GROUP_ID,MESSAGE_THREAD_ID,GITHUB_SHA
          script: |
            # Создаем или обновляем .env файл
            echo "BOT_TOKEN=$BOT_TOKEN" > ~/test-bot/.env
            echo "GROUP_ID=$GROUP_ID" >> ~/test-bot/.env
            echo "MESSAGE_THREAD_ID=$MESSAGE_THREAD_ID" >> ~/test-bot/.env
            echo "GITHUB_SHA=$GITHUB_SHA" >> ~/test-bot/.env
            
            cd ~/test-bot
            docker-compose pull
            docker-compose up -d

  deploy-prod:
    needs: [build, deploy-test]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://t.me/your_bot_username
    
    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          MESSAGE_THREAD_ID: ${{ secrets.MESSAGE_THREAD_ID }}
          GITHUB_SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: BOT_TOKEN,GROUP_ID,MESSAGE_THREAD_ID,GITHUB_SHA
          script: |
            # Создаем или обновляем .env файл
            echo "BOT_TOKEN=$BOT_TOKEN" > ~/prod-bot/.env
            echo "GROUP_ID=$GROUP_ID" >> ~/prod-bot/.env
            echo "MESSAGE_THREAD_ID=$MESSAGE_THREAD_ID" >> ~/prod-bot/.env
            echo "GITHUB_SHA=$GITHUB_SHA" >> ~/prod-bot/.env
            
            cd ~/prod-bot
            docker-compose pull
            docker-compose up -d 